Create toponimos_mexico.txt
sbosio/rla-es pull request #260
Opened 2022-03-26 17:18 UTC by igdfpro

es_MX
This file contains names (toponymics) in nahuatl for mexican cities, towns and places.
Este documento contiene nombres en náhuatl de ciudades, poblaciones y lugares de México.

2022-04-02 16:59 UTC, cosmoscalibur requested changes
La estructura seguida por los topónimos es `toponimos > l10n > es_XX`, donde `XX` es el código ISO de dos letras del país. En este caso, ya existe `es_MX`. Adicional a ello, los nombres deben estar en español, y el _PR_ indica que son nombres náhuatl, por lo cual está fuera del alcance de este proyecto.

2022-04-02 18:32 UTC, igdfpro commented
> La estructura seguida por los topónimos es `toponimos > l10n > es_XX`, donde `XX` es el código ISO de dos letras del país. En este caso, ya existe `es_MX`. Adicional a ello, los nombres deben estar en español, y el _PR_ indica que son nombres náhuatl, por lo cual está fuera del alcance de este proyecto.

Gracias por sus comentarios.
Sí, los nombres son de origen náhuatl, sin embargo se utilizan en el español de México de manera cotidiana, por lo que los consideramos parte del Español; hice este listado de nombres pues los diccionarios marcan como error los nombres proporcionados cuando los escribimos. Nuestras ciudades y lugares tienen estos nombres, por ejemplo "Santa Ana Nopalucan".

2022-04-03 02:18 UTC, cosmoscalibur commented
@igdfpro , importante para fines de revisión y claridad, es que si se usan como parte del nombre en español, es español (a pesar de su origen). La aclaración es importante porque este es un diccionario para español, y el tema de aceptación de vocablos no castellanizados todavía está abierto.
Adicional a ello, se usan son los lemas individuales, ejemplo, "Baja California" se debe registrar bajo los lemas independientes "Baja" y "California". Y como encontrarás en el directorio ya existente de México, se separan acorde el tipo de entidad territorial. Si coincide con los tipos de entidad territorial ya presentes, es hacer unión con esos archivos y no archivos separados, y mantener solo lemas únicos.
Gracias por tu interés de contribuir.

2023-08-10 11:17 UTC, olea commented
@igdfpro estoy completamente por incluir los topónimos mexicanos oficiales. Entiendo que es exactamente el caso.

El único problema a tu listado es la licencia que añades, que es más restrictiva que la [licencia del proyecto](https://github.com/sbosio/rla-es/blob/master/LICENSE.md) e impide legalmente admitir la colaboración.

PS: Personalmente, al publicar listado de palabras yo nunca añado ©. De hecho, la práctica más recomendada para compartir datos abiertos es con declaraciones [Creative Commons 0](https://creativecommons.org/share-your-work/public-domain/cc0/) (CC0), [como, por ejemplo, Wikidata](https://www.wikidata.org/wiki/Wikidata:Licensing#Official_policy).

2023-08-16 11:29 UTC, olea commented
Como no hay respuesta, cierro cautelarmente. Si en el futuro hay que abrirla, pues se abre.

2023-08-16 11:29 UTC, closed without merging