Update NombresMasculinos.txt
sbosio/rla-es pull request #305
Opened 2023-08-22 09:28 UTC by Pompilos

Añado: adminículo, alepín, autoengaño, bailío, balanceo, baldaquino, baldeo, batín, bocoy, bocoyes, buñuelo, centelleo, conciliábulo, desollamiento, gimoteo, húsar, infantilismo, infolio, intensificador, junípero, ladeo, monzón, muecín, martilleo, medallón, minarete, peán, pedigrí, ramadán, rasel, respiro, retazo, rodrigón, sofocón, tándem, tifón, vagabundeo, zarandeo, zodíaco.

OJO: Escribo «tándem/S» aunque no sé si formará el plural como «tandems» o «tándemes», ni cuál es el normativo.

2023-08-22 09:32 UTC, Almorca commented
Es támdems según https://www.fundeu.es/recomendacion/tandem/
Por cierto, enorme el trabajo que estáis haciendo. Ahora no tengo tiempo para colaborar con el proyecto y se agradece que haya gente que siga con él.

2024-10-23 03:19 UTC, cosmoscalibur requested changes

2024-10-23 03:19 UTC, cosmoscalibur commented on ortografia/palabras/RAE/NombresMasculinos.txt
> +bocoyes # Plural de bocoy, no existe bocóis
@Pompilos , estoy revisando, y la regla `/S` funcionaría adecuadamente.
```
SFX S 0         es        [bdhíjlmrúxy]   # abad/es, ababol/es, etc.
```
Si termina en `y`,  añade en el lema sin modificación la terminación `es`, así que este lema lo puedes unificar con el anterior con la regla.

2024-10-23 03:19 UTC, cosmoscalibur commented on ortografia/palabras/RAE/NombresMasculinos.txt
> +tándems # Plural recomendado de tándem, con tilde por ser grupo consonántico final
@Pompilos , veo que este caso realmente debería llevar la regla `/S`, solo que es un error en el archivo de afijos. Efectivamente por terminar en `m` debe agregarse `s` al final, pero la definición en el archivo está mala. Parece como si históricamente el error viniera de aplicar realmente la regla a la excepción de `álbumes`, y realmente esa antes hay que separarla.
Me comentas si haces el cambio general, o si te apoyo con ese y ya solo ajustas la regla aquí.

2024-10-23 03:19 UTC, cosmoscalibur commented on ortografia/palabras/RAE/NombresMasculinos.txt
> -arponero/S
@Pompilos , ¿cuál es el motivo de retirar el lema?

2024-10-24 14:05 UTC, Pompilos commented on ortografia/palabras/RAE/NombresMasculinos.txt
> -arponero/S
Hola, no tengo ni idea de por qué ni quién ni cuándo los eliminó. Pero veo que alguien los ha restaurado.

2024-10-24 14:05 UTC, Pompilos commented on ortografia/palabras/RAE/NombresMasculinos.txt
> +bocoyes # Plural de bocoy, no existe bocóis
Ya he añadido la regla /S que sugieres. Gracias.

2024-10-25 00:59 UTC, cosmoscalibur requested changes

2024-10-25 00:59 UTC, cosmoscalibur commented on ortografia/palabras/RAE/NombresMasculinos.txt
> +tándems # Plural recomendado por la Fundeu de tándem, con tilde por ser grupo consonántico final
@Pompilos , podemos dejar la bandera correcta de una vez, yo esta semana hago el ajuste, pues como te dejé en la observación previa, el error está en la bandera. Este efectivamente debería ser `tándem/S` y generarse bien. O esperas a que yo suba el cambio para que lo puedas verificar

2024-10-25 00:59 UTC, cosmoscalibur commented on ortografia/palabras/RAE/NombresMasculinos.txt
> +arponero/S
@Pompilos , ¿hiciste prueba que el diccionario generado funcione adecuadamente para arponero?
Entiendo que el orden de los lemas es importante, y no sé si la existencia de `arponero` antes de `arpón` era por algún tema de ordenamiento por la tilde.

2024-10-25 05:02 UTC, cosmoscalibur commented on ortografia/palabras/RAE/NombresMasculinos.txt
> +tándems # Plural recomendado por la Fundeu de tándem, con tilde por ser grupo consonántico final
@Pompilos , ya ajusté la definición de la bandera

2024-10-26 01:30 UTC, cosmoscalibur approved these changes

2024-10-26 01:31 UTC, merged