Update toponimos-mundo.txt
sbosio/rla-es pull request #317
Opened 2023-09-20 15:09 UTC by Pompilos

Unifico # Hong Kong, cambio Checa a Chequia y añado: Acaya, Alabama, Alejandría, Amberes, Ámsterdam, Antioquía, Alepo, Aquitania, Arcadia, Argólida, Argos, Asur, Atenas, Babilonia, Bagdad, Basora, Beirut, Belén, Beocia, Bizancio, Bombay, Bósforo, Boston, Burdeos, Calabria, Calais, Cambridge, Campania, Canaán, Cantón, Capadocia, Cartago, Catania, Chequia, Chicago, Cícladas, Creta, Constantinopla, Córcega, Corfú, Corinto, Damasco, Delfos, Delos, Éfeso, Egeo, Elba, Epidauro, Esparta, Estambul, Éufrates, Galia, Ganges, Génova, Gomorra, Harvard, Himalaya, Jericó, Jerusalén, Judea, Lacedemonia, Laconia, Lepanto, Lesbos, Liguria, Lombardía, Londres, Lúxor, Magnesia, Mármara, Mesina, Mesopotamia, Micenas, Milán, Mileto, Nápoles, Nínive, Olimpia, Olimpo, Oxford, Padua, Palermo, Palmira, Parnaso, Peloponeso, Pérgamo, Persépolis, Persia, Platea, Provenza, Pompeya, Rodas, Salamina, Salónica, Samos, Samotracia, Santorini, Sardes, Sicilia, Sidón, Siracusa, Sodoma, Suez, Sumatra, Tebas, Tahití, Tarento, Taormina, Termópilas, Terranova, Tesalónica, Texas, Tigris, Tiro, Tracia, Trafalgar, Troya, Umbría, Ur, Uruk, Véneto, Viena.

2023-09-21 11:14 UTC, Pompilos commented
Pero ya figura en la línea 238 como # República Checa, como nombre compuesto que es. ¿Por qué no se puede retirar Checa? (Entiendo que entre los adjetivos figura el gentilicio checo/GS en minúscula, y que no lo dices por eso.)

2023-09-22 09:17 UTC, Almorca commented
¿Has probado que cuando hay más de una palabra en la misma línea lo coge bien? Creo recordar que daba problemas.

2023-09-22 09:56 UTC, olea commented
> Pero ya figura en la línea 328 como # República Checa, como nombre compuesto que es. 

El texto que empieza por la almohadilla (#) siempre es un comentario y es ignorado completamente por el procesador hunspell. Lo habrás visto en más de un sitio porque así explicamos el porqué de algo. Como sugería @Almorca, hunspell sólo permite una palabra por línea.

> ¿Por qué no se puede retirar Checa? 

Pues, desde mi punto de vista, por completitud en el fichero correspondiente.  Al final los duplicados que hubieran surgido acabarían siendo filtrados en el producto final. No imagino otro impacto perjudicial.

2023-09-22 11:36 UTC, Pompilos commented
Entendí que la almohadilla (que está sistemáticamente en los nombre compuestos) era una forma de identificar a los compuestos, y que funcionaba. Si no funciona, tengo que restaurar Hong Kong (separados) y Checa. Procedo.

2024-10-23 02:57 UTC, cosmoscalibur commented
@Pompilos , las almohadillas no son formas de incluir nombres compuestos. Lo que entiendo de estas almohadillas, y también las tengo así para los topónimos de Colombia, es que al tomar los listados de una fuente externa, me interesa saber que el topónimo está incluido, así no lo esté explícitamente como lema, dado que sus lemas individuales son a su vez sustantivos comunes, por lo que no es necesario añadirlos nuevamente, o si es en la misma línea, como indicación para saber de cual topónimo compuesto es el origen del lema.

Adicional, los códigos usados para compilar el diccionario, remueven las líneas que inician por la almohadilla. Esto se evidencia en `herramientas/remover_comentarios.sh`.

2024-10-23 02:59 UTC, cosmoscalibur requested changes

2024-10-23 02:59 UTC, cosmoscalibur commented on ortografia/palabras/toponimos/toponimos-mundo.txt
> +# Hong Kong
Esto no tiene un efecto, pero si queremos hacer referencia al origen del lema `Hong`, se recomienda incluirlo en la misma línea el comentario.

2024-10-24 13:49 UTC, Pompilos commented on ortografia/palabras/toponimos/toponimos-mundo.txt
> +# Hong Kong
Hola, cosmoscalibur. Al escribir esa línea me guié por lo que habían hecho los editores antes de mí, , como se había hecho con # Guinea Bissáu por ejemplo. Así pues, añadí una línea para Hong, otra para Kong y además la línea # Hong Kong, que ya sé que es un comentario que no se procesa. Entiendo que es una forma de indicar a los editores futuros que ese topónimo ya está incluido, porque se han incluido en las líneas correspondientes cada uno de sus componentes. Puede incluirse el comentario en la misma línea de Hong y de Kong, pero entiendo que habría que hacerlo con todos los comentarios que hay con topónimos compuestos. ¿Hay alguna necesidad u obligación de hacerlo así? Un saludo.

2024-10-25 00:52 UTC, cosmoscalibur commented on ortografia/palabras/toponimos/toponimos-mundo.txt
> +# Hong Kong
@Pompilos , la verdad el comentario es una ayuda y no una obligación. El tema es que si el comentario queda en una línea separada, veo que puede generar la confusión que se discutió en este punto, pero no lo veo como una necesidad para actualizar los previamente existentes. Creo que bien vale la pena añadir esto en la Wiki, yo lo puedo agregar más tarde. Y ya me cuentas si haces ajuste de ese comentario, o si lo pasamos.

2024-10-26 01:29 UTC, merged

2024-12-31 21:38 UTC, RickieES commented
He encontrado un error en el PR. No contiene "Nápoles", sino "Naṕoles".

Lo he corregido en el commit ea82c12.