Update NombresPropiosSiglas.txt
sbosio/rla-es pull request #318
Opened 2023-09-20 15:50 UTC by Pompilos

Cuestiono Xunta, y añado: Acuario, Aladino, Andrómeda, Aries, Belcebú, Borbón, Caín, Cáncer, Capricornio, Carlomagno, Cleopatra, Damocles, Deuteronomio, Eclesiastés, Escorpio, Euclides, Fidias, Géminis, Hamlet, Isaías, Job, Jonás, Josué, Juan, Judit, Leo, Libra, Linux, Malaquías, Medea, Neptuno, Odisea, Odiseo, Orión, Paracelso, Perseo, Pléyades, Piscis, Prometeo, Sagitario, Sirio, Tauro, Teseo, Vega, Virgo, Vitruvio.

2023-09-21 10:16 UTC, olea commented
Mi único comentario es que las discusiones de términos las hagamos a través de boletines de Github o del grupo Telegram, no a través del código fuente :-)

2023-09-21 11:24 UTC, Pompilos commented
Hola. En «Xunta # revisar» seguí el modelo de otras palabras que figuran con comentario, pero me parece bien lo que dices. No acabo de saber si esto es el boletín de Github al que te refieres. Si lo es, procedo a discutir términos:

1) Darussalam es un topónimo. Además es parte del nombre oficial "Negara Brunei Darussalam", que es español llamamos Brunéi. Debe desaparecer, igual que no incluimos United Kingdom (en inglés), sino Reino Unido.
2) En Mercosur creo que no hay nada que revisar, es correcto.
3) Oscar sin tilde es una falta de ortografía en español, y debe quitarse (si está bien en inglés, habrá que quitarlo por no estar en español).
4) Xunta no es nombre propio ni está en español y debe desaparecer.

¿Coincidimos?

2023-09-27 11:09 UTC, Gdakgdak22 approved these changes

2023-10-02 03:32 UTC, Gdakgdak22 approved these changes

2024-10-23 02:28 UTC, cosmoscalibur requested changes

2024-10-23 02:28 UTC, cosmoscalibur commented on ortografia/palabras/noRAE/NombresPropiosSiglas.txt
> +Xunta # revisar (nombre común en otro idioma, extranjerismo)
@Pompilos , yo veo que podemos eliminar esto.
Entiendo que "Xunta" tal como indicas, es nombre común en otro idioma, por lo cual se puede depurar. Y en caso de considerarse como extranjerismo, debería ser en `es_ES`, porque esto puede tener impacto por el gallego, pero no para las regiones de América.

2024-10-24 14:01 UTC, Pompilos commented on ortografia/palabras/noRAE/NombresPropiosSiglas.txt
> +Xunta # revisar (nombre común en otro idioma, extranjerismo)
He eliminado Xunta.

2024-10-25 00:48 UTC, cosmoscalibur approved these changes

2024-10-25 00:48 UTC, merged

2024-12-31 21:38 UTC, RickieES commented
En el commit se omitió el último nombre de esta lista, Vitruvio.

Lo he corregido en el commit ea82c12.