Nombres y apellidos según INE (españa)
sbosio/rla-es pull request #328
Opened 2024-09-16 09:38 UTC by amunizp

Propuesta de nombres propios como se comentó en la incidencia: #265

2024-09-29 23:31 UTC, cosmoscalibur requested changes
@amunizp , tal como se explicó en https://github.com/sbosio/rla-es/issues/265#issuecomment-2350830195, esto corresponde al archivo `NombresPropiosSiglas.txt`, y no a `ApellidosINE.txt` ni `NombresPropiosINE.txt`. Nuestra estructura tiene los nombres propios (o sea, nombres y apellidos) con siglas en el mismo archivo y sin distinguir la fuente. Respecto a la validación de fuente, el PR puede incluir la información respectiva y así puede ser validada en revisión, pero además tener la trazabilidad en el historial de GitHub.
Respetar la estructura de los archivos del proyecto.

2024-09-30 08:31 UTC, amunizp commented
Cambios hechos. Muchas gracias lamento la poca inforomación. Añadir que información sobre el origen de la lista esta está también en el cabecero de la misma.

2024-10-08 02:50 UTC, cosmoscalibur commented
@amunizp , persiste que son miles de líneas. Esto implica que no hay un criterio de validación.
Cuando se usan elementos que provienen de algún _corpus_, se suele usar un criterio de frecuencia relativa de tal forma que se justifique la adición respecto al volumen de información y no hacer que las extensiones sean muy pesadas, sabiendo que pueden existir elementos poco usuales y que por ende, aportan poco valor.
Adicional, eso impide hacer revisión real del PR, al punto, que la misma visualización de GitHub del archivo falla, y no tengo como verificar fácilmente, que los lemas que borraste de archivos ya existentes, estén agregados en el archivo unificado.

2024-10-08 02:53 UTC, cosmoscalibur requested changes
Se eliminaron sin justificación dos archivos de sustantivos.
Se agregó archivo de miles de líneas que imposibilita revisión, adicional del incremento del tamaño de la extensión sin valorar adecuadamente la frecuencia relativa de los lemas añadidos.

2024-10-08 08:21 UTC, amunizp commented
Muchas gracias por los comentarios.

Sobre los archivos eliminados son los que se pidió eliminar en el comentario anterior. Por lo tanto considero que lo más útil en este punto es cancelar este PR y pasar a límpio. Esto evitará confusiones.

Sobre la justificación de frecuencia de uso de cada nombre o apellido en la lista. Estas palabras las tienen por lo menos 100 personas que nacieron en España. Cada persona y la gente que la conoce en su casa a la hora de comer usará esos nombres y apellidos miles de veces a lo largo de sus vidas. Estimo que  estos se usan más que las palabras en desuso aceptados en el Diccionario de la Real Academia Española. Considero esta una justificación suficiente. 

Relativo al tamaño del archivo y como afecta eso a los programas que usan el diccionario supongo que se verá a la hora de compilar si afecta la eficacia. Si es así, puedo proponer usar los nombres y apellidos con frecuencia superior a 500 para reducir la carga. Alternativamente he visto que en otros diccionarios hay más archivos por lo que podría separar en categorías de frecuencia. *NombresPropiosSiglas.txt* podría separarse en distintos archivos como mi propuesta inicial he visto que ES_CO tiene más archivos que ES_ES. También he visto que el diccionario inglés australiano incluye una manera de añadir base de datos: http://wordlist.aspell.net/. Estás son propuestas técnicas que, en mi humilde opinión, se pueden solucionar pero caen fuera de este PR. Pero no me quería rendir en vísperas y propongo mantenerlo en un archivo grande de momento.

Lo que nos trae a validación. Supongo que damos por válidos los archivos que provee el Instituto Nacional de Estadística (INE) de España . Lo que quedaría por demostrar es que no he añadido o quitado alguna palabra de las listas. Para ello propongo crear un pequeño programa simple y comprensible en Python que permita validar la lista en el PR con la lista en INE. 

Concluyendo, si no es inconveniente me gustaría proponer lo siguiente en orden de prioridad:

1) Crear un pequeño programa simple en Python que permita validar el archivo txt con el archivo que provee INE.
2) Mantener un sólo archivo grande NombresPropiosSiglas.txt .
3) Cerrar este PR y crear uno nuevo con las explicaciones aquí detalladas tanto en el comentario como en el cabecero del archivo a modo de comentario "#".

Una vez más agradezco el tiempo dedicado a esta propuesta.

2024-10-23 02:22 UTC, cosmoscalibur commented
@amunizp , se pidió eliminar `ApellidosINE.txt` y `NombresPropiosINE.txt` que eran archivos nuevos en la propuesta por no cumplir el esquema del proyecto, pero eliminaste además acorde al PR dos archivos propios del proyecto también que son `NombresFemeninos.txt` y `NombresMasculinos.txt`, que nada se relacionaban con el PR, ya que el PR es de nombres propios, pero los archivos que borraste son de sustantivos comunes.
La justificación de frecuencia de uso, es que la existencia en 100 personas y el uso que da una persona particular, no habla del beneficio total de cargar ese peso a toda la comunidad. Y es por eso que, allí sigue que si se hace un proceso manual, es claro que las adiciones seguirán acorde a la necesidad real de uso, sin contar que los nombres propios en sí mismos no poseen ortografía, por lo cual tienen menor beneficio que los lemas RAE.
El tema no se relaciona con la compilación, y la partición en archivos no tiene un efecto. El tema se asocia a la distribución de los archivos en las extensiones y en el uso por los usuarios. Y justamente esto ya ha estado en otros momentos de discusión en el proyecto y se ha optado por no automatizaciones masivas, que escapen a la revisión manual de los lemas.
No es clara la mención a número de archivos. El tema es que los archivos corresponden a categorías gramaticales, no a divisiones por tamaños de lemas.

Te recomiendo las lecturas para contribuir en el proyecto

- [Criterios usados para admitir palabras](https://github.com/sbosio/rla-es/wiki/C%C3%B3mo-colaborar-con-RLA-ES-y-con-el-corrector-ortogr%C3%A1fico#criterios-usados-para-admitir-palabras).
- [Clasificación de los lemas](https://github.com/sbosio/rla-es/wiki/Clasificaci%C3%B3n-de-lemas).

Respecto al _script_, este estaría fuera del alcance de este repositorio, y justamente como los lemas no cumplirían los criterios de aceptación de palabras, no habría mucho sentido tampoco en los lemas masivos.

Para su aceptación, se recomienda la validación de listas más cortas. Ejemplo, hice la validación con el listado que se dispone de los 100 nombres más comunes de hombres y de mujeres en España, y esto ya cubriría al 91 % de las mujeres y el 96 % de los hombres.

2024-10-26 13:23 UTC, RickieES commented
Estoy mirando el archivo propuesto y no va a aceptarse nunca en este proyecto sin una enorme cantidad de cambios. Yo recomiendo sinceramente desistir de este PR, porque requiere un esfuerzo ímprobo.

Respecto a lo que no se puede aceptar:

- Los comentarios añadidos al principio, que supongo que provienen de la fuente original del INE, no tienen razón de permanecer en el repositorio y habría que eliminarlos. Esto es lo de menos, pero como está al principio, lo comento para que no se me olvide.
- No puede haber más de un lema por línea. Nombres compuestos como María del Carmen, Mari Carmen o Carmen María son relevantes individualmente a los efectos estadísticos, pero no sirven en un diccionario. Solo importa María y Carmen.
- Los lemas no pueden ir en mayúsculas, salvo que por ser siglas o acrónimos deban escribirse siempre así (como IBM, ONU o NASA).
- Y, por supuesto, debe respetarse la acentuación. De ninguna manera podemos aceptar "MARIA" o "Maria" en un diccionario ortográfico, cuando la redacción correcta es "María".

No cuestiono la validez de la información proporcionada por el INE, sino la forma en que se debe incorporar al repositorio. Aparte de eso, con una lista depurada tendríamos que plantearnos el umbral a partir del cual incorporar los lemas. Como digo, hay mucho trabajo previo antes de poder incluir este contenido.

2024-10-26 16:03 UTC, closed without merging

2024-10-26 16:03 UTC, cosmoscalibur commented
Concuerdo con esto, y proceder mejor con cerrar con los argumentos discutidos en el PR.